### ISSUE TITLE
Seasons in the Sea: study design & deployment

### ISSUE THREAD

**Issue by scottveirs** [salish-sea/salish-sea.github.io#1]
**How can we collectively aggregate and visualize marine mammal observations to depict the annual patterns of distribution and behavior?** 

##Tasks:

- [ ] [Discuss ideas and scope](https://github.com/orgs/salish-sea/discussions/1)
- [ ] Discuss data architecture and study user personae
- [ ] Discuss & test open source tools, modular code design, and tech stack of inspiring pioneers
  - [ ] Experiment with [Knight Lab's Timeline tool](https://timeline.knightlab.com/) (javascript): [Google spreadsheet for Salish Sea marine mammals](https://docs.google.com/spreadsheets/d/1wtIcfbHsqZOCrV8SWvq31_dt5LT-Cxs89uta_gr2aLI/edit#gid=0) | [Web-based timeline demo](https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1wtIcfbHsqZOCrV8SWvq31_dt5LT-Cxs89uta_gr2aLI&font=Default&lang=en&initial_zoom=2&height=650)
- [ ] Discuss compatibility with end-user communication channels (e.g. PSEMP MMWG web/3 presence)
- [ ] Establish repository/ies for the underlying data and visualization
- [ ] Populate data repository/ies
- [ ] Develop initial visualization
- [ ] Betatest MVP
- [ ] Refine through user-centered design and feature-based development

This project idea was inspired by the [Seasons in the Sea project](http://www.seasonsinthesea.com/timelines/mammals.shtml) which depicts seasonal patterns in California ecosystems:

![Image](https://user-images.githubusercontent.com/14044595/213583995-df4d34cb-15d6-4c9a-8fd5-d49c3ad7e62a.png)
